version: '3.8'
services:
  # React App
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    stdin_open: true
    tty: true

  # Node.js App
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=mongo
      - DB_USER=rootuser
      - DB_PASS=rootpass
      - DB_NAME=seorotown
    depends_on:
      - mongo

  # MongoDB Database
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass