# docker-compose.yml


services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/seorotown

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb: 
    image: mongo:latest
    container_name: seorotown_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 