name: "✨ Feature"
description: "새로운 기능 추가"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: ✅ 작업할 내용
      description: 아래 항목을 체크해주세요.
      options:
        - label: 친구페이지 → 마이페이지로 변경
        - label: 게시글 리스트 열람
        - label: 댓글 페이지 열람
        - label: 팔로우 기능
        - label: 팔로잉 기능
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
